### ISSUE TITLE
Move user-manual in-tree

### ISSUE THREAD

**Issue by moy** [Git-Mediawiki/Git-Mediawiki#9]
The documentation is currently maintained as a wiki : https://github.com/moy/Git-Mediawiki/wiki/User-manual

It would be nice to move this in the source tree, using asciidoc for consistency with other Git documents. This way, new features could introduce code and documentation in the same commit.

**Comment by anarcat** [comment]
+1. i absolutely love this project, but it's kind of ironic that we can't access the documentation offline, which is, i think, one of the killer features of this. :)

**Comment by anarcat** [comment]
a few ideas on how to handle this:

1. keep the wiki separate, but add it as a [submodule in the main repo](http://stackoverflow.com/questions/6941688/how-to-integrate-a-github-wiki-into-the-main-project)
2. move the wiki into the main repository completely, and points links there - which would still allow users to edit the documentation freely, but it then goes through the pull request process instead

i would favor the second solution, if only because it simplifies things greatly.

**Comment by anarcat** [comment]
so do we want to keep the wiki or do we want to merge the docs into the main tree?

**Comment by moy** [comment]
No strong opinion from me, but I'd slightly favor the second solution too. The wiki was very helpful by the early times of Git-Mediawiki where we didn't have the same quality expectation from code and documentation (i.e. I did want to be able to do quick and dirty edits on the wiki but I also wanted a picky reviewing process on the code), but this is probably not true anymore today. And once the code is managed here, doing a pull-request is not much harder than editing a wiki (especially since GitHub has an "edit" button for text pages).

**Comment by anarcat** [comment]
oh, and i turned off the wiki here - it's still there (if i turn it back on, data is still there), just hidden from view.
